import { Inter } from "next/font/google"
import { MainNav } from "@/components/MainNav"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="max-w-2xl mx-auto z-10 top-0 ">
                    <MainNav className="fixed" />
                </header>
                {children}
                <footer className="flex justify-center">Hecho por izimport.com</footer>

            </body>
        </html>
    )
}
